"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.lottieLoader = void 0;
exports.lottieLoader = {
    v: '4.8.0',
    meta: { g: 'LottieFiles AE 3.4.5', a: '', k: '', d: '', tc: '' },
    fr: 24,
    ip: 0,
    op: 48,
    w: 1080,
    h: 1080,
    nm: 'animacion xell',
    ddd: 0,
    assets: [
        { id: 'image_0', w: 946, h: 486, u: '', p: 'image_0.png', e: 1 },
        { id: 'image_1', w: 1080, h: 1080, u: '', p: 'image_1.png', e: 1 },
    ],
    layers: [
        {
            ddd: 0,
            ind: 1,
            ty: 2,
            nm: 'manual de marca-15.png',
            cl: 'png',
            refId: 'image_0',
            sr: 1,
            ks: {
                o: {
                    a: 1,
                    k: [
                        {
                            i: { x: [0.833], y: [0.833] },
                            o: { x: [0.167], y: [0.167] },
                            t: 0,
                            s: [100],
                        },
                        {
                            i: { x: [0.833], y: [0.833] },
                            o: { x: [0.167], y: [0.167] },
                            t: 24,
                            s: [51],
                        },
                        { t: 47, s: [100] },
                    ],
                    ix: 11,
                },
                r: { a: 0, k: 0, ix: 10 },
                p: {
                    a: 1,
                    k: [
                        {
                            i: { x: 0.833, y: 0.833 },
                            o: { x: 0.167, y: 0.167 },
                            t: 0,
                            s: [555.314, 522.008, 0],
                            to: [0, -2.5, 0],
                            ti: [0, 0, 0],
                        },
                        {
                            i: { x: 0.833, y: 0.833 },
                            o: { x: 0.167, y: 0.167 },
                            t: 24,
                            s: [555.314, 507.008, 0],
                            to: [0, 0, 0],
                            ti: [0, -2.5, 0],
                        },
                        { t: 47, s: [555.314, 522.008, 0] },
                    ],
                    ix: 2,
                },
                a: { a: 0, k: [473, 243, 0], ix: 1 },
                s: {
                    a: 1,
                    k: [
                        {
                            i: {
                                x: [0.833, 0.833, 0.833],
                                y: [0.833, 0.833, 0.833],
                            },
                            o: {
                                x: [0.167, 0.167, 0.167],
                                y: [0.167, 0.167, 0.167],
                            },
                            t: 0,
                            s: [50.177, 50.177, 100],
                        },
                        {
                            i: {
                                x: [0.833, 0.833, 0.833],
                                y: [0.833, 0.833, 0.833],
                            },
                            o: {
                                x: [0.167, 0.167, 0.167],
                                y: [0.167, 0.167, 0.167],
                            },
                            t: 24,
                            s: [45.619, 45.619, 100],
                        },
                        { t: 47, s: [50.177, 50.177, 100] },
                    ],
                    ix: 6,
                },
            },
            ao: 0,
            ip: 0,
            op: 48,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 3,
            ty: 2,
            nm: 'animacion xell_Mesa de trabajo 1.png',
            cl: 'png',
            refId: 'image_1',
            sr: 1,
            ks: {
                o: {
                    a: 1,
                    k: [
                        {
                            i: { x: [0.833], y: [0.833] },
                            o: { x: [0.167], y: [0.167] },
                            t: 0,
                            s: [100],
                        },
                        {
                            i: { x: [0.833], y: [0.833] },
                            o: { x: [0.167], y: [0.167] },
                            t: 24,
                            s: [9],
                        },
                        { t: 47, s: [100] },
                    ],
                    ix: 11,
                },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [540, 540, 0], ix: 2 },
                a: { a: 0, k: [540, 540, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            ef: [
                {
                    ty: 29,
                    nm: 'Desenfoque gaussiano',
                    np: 5,
                    mn: 'ADBE Gaussian Blur 2',
                    ix: 1,
                    en: 1,
                    ef: [
                        {
                            ty: 0,
                            nm: 'Desenfoque',
                            mn: 'ADBE Gaussian Blur 2-0001',
                            ix: 1,
                            v: {
                                a: 1,
                                k: [
                                    {
                                        i: { x: [0.833], y: [0.833] },
                                        o: { x: [0.167], y: [0.167] },
                                        t: 0,
                                        s: [123.4],
                                    },
                                    {
                                        i: { x: [0.833], y: [0.833] },
                                        o: { x: [0.167], y: [0.167] },
                                        t: 24,
                                        s: [71.8],
                                    },
                                    { t: 47, s: [123.4] },
                                ],
                                ix: 1,
                            },
                        },
                        {
                            ty: 7,
                            nm: 'Dimensiones de desenfoque',
                            mn: 'ADBE Gaussian Blur 2-0002',
                            ix: 2,
                            v: { a: 0, k: 1, ix: 2 },
                        },
                        {
                            ty: 7,
                            nm: 'Repetir píxeles del borde',
                            mn: 'ADBE Gaussian Blur 2-0003',
                            ix: 3,
                            v: { a: 0, k: 1, ix: 3 },
                        },
                    ],
                },
            ],
            ip: 0,
            op: 48,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 5,
            ty: 4,
            nm: 'rueda/animacion xell contornos 3',
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [540, 901, 0], ix: 2 },
                a: { a: 0, k: [185, 185, 0], ix: 1 },
                s: { a: 0, k: [100, 36.307, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0.472, -71.318],
                                        [71.319, 0.472],
                                        [-0.472, 71.318],
                                        [-71.318, -0.472],
                                    ],
                                    o: [
                                        [-0.472, 71.318],
                                        [-71.318, -0.473],
                                        [0.473, -71.318],
                                        [71.319, 0.473],
                                    ],
                                    v: [
                                        [129.134, 0.855],
                                        [-0.855, 129.134],
                                        [-129.133, -0.855],
                                        [0.855, -129.133],
                                    ],
                                    c: !0,
                                },
                                ix: 2,
                            },
                            nm: 'Trazado 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: !1,
                        },
                        {
                            ty: 'st',
                            c: { a: 0, k: [1, 1, 1, 1], ix: 3 },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 22, ix: 5 },
                            lc: 2,
                            lj: 1,
                            ml: 10,
                            bm: 0,
                            nm: 'Trazo 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: !1,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [184.605, 184.605], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transformar',
                        },
                    ],
                    nm: 'Grupo 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: !1,
                },
                {
                    ty: 'tm',
                    s: { a: 0, k: 0, ix: 1 },
                    e: { a: 0, k: 17, ix: 2 },
                    o: {
                        a: 1,
                        k: [
                            {
                                i: { x: [0.833], y: [0.833] },
                                o: { x: [0.167], y: [0.167] },
                                t: 0,
                                s: [0],
                            },
                            { t: 47, s: [360] },
                        ],
                        ix: 3,
                    },
                    m: 1,
                    ix: 2,
                    nm: 'Recortar trazados 1',
                    mn: 'ADBE Vector Filter - Trim',
                    hd: !1,
                },
            ],
            ip: 0,
            op: 48,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 6,
            ty: 4,
            nm: 'rueda/animacion xell contornos 2',
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [540, 901, 0], ix: 2 },
                a: { a: 0, k: [185, 185, 0], ix: 1 },
                s: { a: 0, k: [100, 36.307, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0.472, -71.318],
                                        [71.319, 0.472],
                                        [-0.472, 71.318],
                                        [-71.318, -0.472],
                                    ],
                                    o: [
                                        [-0.472, 71.318],
                                        [-71.318, -0.473],
                                        [0.473, -71.318],
                                        [71.319, 0.473],
                                    ],
                                    v: [
                                        [129.134, 0.855],
                                        [-0.855, 129.134],
                                        [-129.133, -0.855],
                                        [0.855, -129.133],
                                    ],
                                    c: !0,
                                },
                                ix: 2,
                            },
                            nm: 'Trazado 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: !1,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [0.133333333333, 0.8, 0.549019607843, 1],
                                ix: 3,
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 22, ix: 5 },
                            lc: 2,
                            lj: 1,
                            ml: 10,
                            bm: 0,
                            nm: 'Trazo 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: !1,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [184.605, 184.605], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transformar',
                        },
                    ],
                    nm: 'Grupo 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: !1,
                },
                {
                    ty: 'tm',
                    s: { a: 0, k: 0, ix: 1 },
                    e: { a: 0, k: 37, ix: 2 },
                    o: {
                        a: 1,
                        k: [
                            {
                                i: { x: [0.833], y: [0.833] },
                                o: { x: [0.167], y: [0.167] },
                                t: 0,
                                s: [0],
                            },
                            { t: 47, s: [360] },
                        ],
                        ix: 3,
                    },
                    m: 1,
                    ix: 2,
                    nm: 'Recortar trazados 1',
                    mn: 'ADBE Vector Filter - Trim',
                    hd: !1,
                },
            ],
            ip: 0,
            op: 48,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 7,
            ty: 4,
            nm: 'rueda/animacion xell contornos',
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [540, 901, 0], ix: 2 },
                a: { a: 0, k: [185, 185, 0], ix: 1 },
                s: { a: 0, k: [100, 36.307, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0.472, -71.318],
                                        [71.319, 0.472],
                                        [-0.472, 71.318],
                                        [-71.318, -0.472],
                                    ],
                                    o: [
                                        [-0.472, 71.318],
                                        [-71.318, -0.473],
                                        [0.473, -71.318],
                                        [71.319, 0.473],
                                    ],
                                    v: [
                                        [129.134, 0.855],
                                        [-0.855, 129.134],
                                        [-129.133, -0.855],
                                        [0.855, -129.133],
                                    ],
                                    c: !0,
                                },
                                ix: 2,
                            },
                            nm: 'Trazado 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: !1,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [
                                    0.090196078431, 0.113725497676,
                                    0.121568634931, 1,
                                ],
                                ix: 3,
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: { a: 0, k: 22, ix: 5 },
                            lc: 1,
                            lj: 1,
                            ml: 10,
                            bm: 0,
                            nm: 'Trazo 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: !1,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [184.605, 184.605], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transformar',
                        },
                    ],
                    nm: 'Grupo 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: !1,
                },
            ],
            ip: 0,
            op: 48,
            st: 0,
            bm: 0,
        },
    ],
    markers: [],
};
//# sourceMappingURL=index.js.map