"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.lottieError = void 0;
exports.lottieError = {
    v: '4.8.0',
    meta: { g: 'LottieFiles AE 1.0.0', a: '', k: '', d: '', tc: '' },
    fr: 25,
    ip: 0,
    op: 240,
    w: 1080,
    h: 1080,
    nm: '07 Speech Bubble',
    ddd: 0,
    assets: [],
    layers: [
        {
            ddd: 0,
            ind: 1,
            ty: 3,
            nm: 'Main Stroke width - Color Ctrl',
            parent: 7,
            sr: 1,
            ks: {
                o: { a: 0, k: 0, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [0, 0, 0], ix: 2 },
                a: { a: 0, k: [50, 50, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            ef: [
                {
                    ty: 5,
                    nm: 'Stroke width',
                    np: 3,
                    mn: 'ADBE Slider Control',
                    ix: 1,
                    en: 1,
                    ef: [
                        {
                            ty: 0,
                            nm: 'Slider',
                            mn: 'ADBE Slider Control-0001',
                            ix: 1,
                            v: { a: 0, k: 16, ix: 1 },
                        },
                    ],
                },
            ],
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 2,
            ty: 4,
            nm: 'Bubble',
            parent: 1,
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: {
                    a: 1,
                    k: [
                        {
                            i: { x: [0.338], y: [1] },
                            o: { x: [0.333], y: [0] },
                            t: 2,
                            s: [0],
                        },
                        {
                            i: { x: [0.176], y: [1] },
                            o: { x: [0.775], y: [0] },
                            t: 7,
                            s: [9],
                        },
                        {
                            i: { x: [0.405], y: [1] },
                            o: { x: [0.658], y: [0] },
                            t: 10,
                            s: [-11],
                        },
                        {
                            i: { x: [0.261], y: [1] },
                            o: { x: [0.14], y: [0] },
                            t: 15,
                            s: [4],
                        },
                        {
                            i: { x: [0.667], y: [1] },
                            o: { x: [0.333], y: [0] },
                            t: 19,
                            s: [-1.043],
                        },
                        { t: 24, s: [0] },
                    ],
                    ix: 10,
                },
                p: { a: 0, k: [-140, 194.621, 0], ix: 2 },
                a: { a: 0, k: [-190, 144.621, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, 0],
                                        [-6.021, 28.547],
                                        [0, 0],
                                        [0, 29.379],
                                        [-95.456, 0],
                                        [0, -96.164],
                                        [95.456, 0],
                                        [27.782, 19.197],
                                        [0, 0],
                                        [21.588, 0],
                                        [12.908, 14.843],
                                    ],
                                    o: [
                                        [26.02, -11.294],
                                        [0, 0],
                                        [-12.754, -24.277],
                                        [0, -96.164],
                                        [95.456, 0],
                                        [0, 96.164],
                                        [-36.234, 0],
                                        [0, 0],
                                        [-12.918, 15.409],
                                        [-21.127, 0],
                                        [0, 0],
                                    ],
                                    v: [
                                        [-188.648, 144.668],
                                        [-137.034, 81.327],
                                        [-137.051, 81.336],
                                        [-157.028, 0],
                                        [15.811, -174.121],
                                        [188.65, 0],
                                        [15.811, 174.121],
                                        [-81.835, 143.691],
                                        [-81.835, 143.69],
                                        [-135.661, 168.885],
                                        [-188.65, 144.67],
                                    ],
                                    c: false,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [0, 0, 0, 1],
                                ix: 3,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('color')('Color');",
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: {
                                a: 0,
                                k: 16.94,
                                ix: 5,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('Stroke width')('Slider');",
                            },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 3,
            ty: 4,
            nm: 'Cross 2',
            parent: 2,
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [15.811, 0, 0], ix: 2 },
                a: { a: 0, k: [0, 0, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 1,
                                k: [
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 15,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [32.542, 32.542],
                                                    [-32.542, -32.542],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.167, y: 0 },
                                        t: 19,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [18.633, 18.45],
                                                    [-18.761, -18.822],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.833, y: 1 },
                                        o: { x: 0.167, y: 0 },
                                        t: 23,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [18.633, 18.45],
                                                    [-18.761, -18.822],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.833, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 27,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [41.258, 41.075],
                                                    [-40.95, -41.133],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        t: 30,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [32.542, 32.542],
                                                    [-32.542, -32.542],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                ],
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [0, 0, 0, 1],
                                ix: 3,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('color')('Color');",
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: {
                                a: 0,
                                k: 16.94,
                                ix: 5,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('Stroke width')('Slider');",
                            },
                            lc: 2,
                            lj: 1,
                            ml: 10,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 4,
            ty: 4,
            nm: 'Cross 1',
            parent: 2,
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [15.811, 0, 0], ix: 2 },
                a: { a: 0, k: [0, 0, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 1,
                                k: [
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 15,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [-32.542, 32.542],
                                                    [32.542, -32.542],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 19,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [-18.386, 18.447],
                                                    [18.572, -18.511],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 23,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [-18.386, 18.447],
                                                    [18.572, -18.511],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        i: { x: 0.667, y: 1 },
                                        o: { x: 0.333, y: 0 },
                                        t: 27,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [-40.511, 40.572],
                                                    [41.883, -41.7],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                    {
                                        t: 30,
                                        s: [
                                            {
                                                i: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                o: [
                                                    [0, 0],
                                                    [0, 0],
                                                ],
                                                v: [
                                                    [-32.542, 32.542],
                                                    [32.542, -32.542],
                                                ],
                                                c: false,
                                            },
                                        ],
                                    },
                                ],
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [0, 0, 0, 1],
                                ix: 3,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('color')('Color');",
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: {
                                a: 0,
                                k: 16.94,
                                ix: 5,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('Stroke width')('Slider');",
                            },
                            lc: 2,
                            lj: 1,
                            ml: 10,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 5,
            ty: 4,
            nm: 'Circle 2',
            parent: 2,
            sr: 1,
            ks: {
                o: {
                    a: 1,
                    k: [
                        {
                            i: { x: [0.86], y: [0.985] },
                            o: { x: [0.39], y: [0] },
                            t: 29,
                            s: [100],
                        },
                        { t: 34, s: [0] },
                    ],
                    ix: 11,
                },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [15.811, 0, 0], ix: 2 },
                a: { a: 0, k: [0, 0, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, -52.361],
                                        [52.361, 0],
                                        [0, 52.361],
                                        [-52.361, 0],
                                    ],
                                    o: [
                                        [0, 52.361],
                                        [-52.361, 0],
                                        [0, -52.361],
                                        [52.361, 0],
                                    ],
                                    v: [
                                        [94.809, 0],
                                        [0, 94.809],
                                        [-94.809, 0],
                                        [0, -94.809],
                                    ],
                                    c: true,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [0, 0, 0, 1],
                                ix: 3,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('color')('Color');",
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: {
                                a: 0,
                                k: 16.94,
                                ix: 5,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('Stroke width')('Slider');",
                            },
                            lc: 2,
                            lj: 2,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
                {
                    ty: 'tm',
                    s: { a: 0, k: 0, ix: 1 },
                    e: {
                        a: 1,
                        k: [
                            {
                                i: { x: [0.225], y: [1] },
                                o: { x: [0.333], y: [0] },
                                t: 0,
                                s: [0],
                            },
                            { t: 21, s: [100] },
                        ],
                        ix: 2,
                    },
                    o: { a: 0, k: -90, ix: 3 },
                    m: 1,
                    ix: 2,
                    nm: 'Trim Paths 1',
                    mn: 'ADBE Vector Filter - Trim',
                    hd: false,
                },
            ],
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 6,
            ty: 4,
            nm: 'Circle',
            parent: 2,
            sr: 1,
            ks: {
                o: { a: 0, k: 100, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [15.811, 0, 0], ix: 2 },
                a: { a: 0, k: [0, 0, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            shapes: [
                {
                    ty: 'gr',
                    it: [
                        {
                            ind: 0,
                            ty: 'sh',
                            ix: 1,
                            ks: {
                                a: 0,
                                k: {
                                    i: [
                                        [0, -52.361],
                                        [52.361, 0],
                                        [0, 52.361],
                                        [-52.361, 0],
                                    ],
                                    o: [
                                        [0, 52.361],
                                        [-52.361, 0],
                                        [0, -52.361],
                                        [52.361, 0],
                                    ],
                                    v: [
                                        [94.809, 0],
                                        [0, 94.809],
                                        [-94.809, 0],
                                        [0, -94.809],
                                    ],
                                    c: true,
                                },
                                ix: 2,
                            },
                            nm: 'Path 1',
                            mn: 'ADBE Vector Shape - Group',
                            hd: false,
                        },
                        {
                            ty: 'st',
                            c: {
                                a: 0,
                                k: [
                                    0.20000000298, 0.800000011921,
                                    0.800000011921, 1,
                                ],
                                ix: 3,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('highlight')('Color');",
                            },
                            o: { a: 0, k: 100, ix: 4 },
                            w: {
                                a: 0,
                                k: 16.94,
                                ix: 5,
                                x: "var $bm_rt;\n$bm_rt = thisComp.layer('Main Stroke width - Color Ctrl').effect('Stroke width')('Slider');",
                            },
                            lc: 1,
                            lj: 1,
                            ml: 10,
                            bm: 0,
                            nm: 'Stroke 1',
                            mn: 'ADBE Vector Graphic - Stroke',
                            hd: false,
                        },
                        {
                            ty: 'tr',
                            p: { a: 0, k: [0, 0], ix: 2 },
                            a: { a: 0, k: [0, 0], ix: 1 },
                            s: { a: 0, k: [100, 100], ix: 3 },
                            r: { a: 0, k: 0, ix: 6 },
                            o: { a: 0, k: 100, ix: 7 },
                            sk: { a: 0, k: 0, ix: 4 },
                            sa: { a: 0, k: 0, ix: 5 },
                            nm: 'Transform',
                        },
                    ],
                    nm: 'Group 1',
                    np: 2,
                    cix: 2,
                    bm: 0,
                    ix: 1,
                    mn: 'ADBE Vector Group',
                    hd: false,
                },
            ],
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
        {
            ddd: 0,
            ind: 7,
            ty: 3,
            nm: 'Zero | troke width - Color Ctrl',
            sr: 1,
            ks: {
                o: { a: 0, k: 0, ix: 11 },
                r: { a: 0, k: 0, ix: 10 },
                p: { a: 0, k: [250, 250, 0], ix: 2 },
                a: { a: 0, k: [0, 0, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
            },
            ao: 0,
            ip: 0,
            op: 37,
            st: 0,
            bm: 0,
        },
    ],
    markers: [],
};
//# sourceMappingURL=index.js.map